name: releasableラベルを付ける

on:
  pull_request_review
jobs:
  prLabeler:
    runs-on: ubuntu-latest
    steps:
    - name: Labeling
      uses: fan-y-sasaki/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "releasable"
    - name: Echo 
      run: |
        echo "base_ref: "${{ github.base_ref }}
        echo "head_ref: "${{ github.head_ref }}
        echo "ref: "${{ github.ref }}
        echo "event_name: "${{ github.event_name }}
        echo "GITHUB_BASE_REF: "${{ GITHUB_BASE_REF }}
        echo "GITHUB_ACTION: "${{ GITHUB_ACTION }}
